---
name: lint

on:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:
    types: [opened, edited, synchronize, reopened, review_requested]

jobs:
  php-lint:
    name: PHP lint 8.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP syntax checker 8.2
        uses: prestashop/github-action-php-lint/8.2@master

#  phpmd:
#    name: PHPMD
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        
#      - name: PHP Mess Detector
#        uses: php-actions/phpmd@v1
#        with:
#          php_version: 8.2
#          path: ./
#          output: text
#          ruleset: test/phpmd/ruleset.xml

  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: PHP Code Sniffer
        uses: php-actions/phpcs@v1
        with:
          php_version: 8.2
          path: ./
          standard: PSR12
          ignore: livestats.blade.php,config.blade.php
          exclude: Squiz.Functions.MultiLineFunctionDeclaration

# Figure out later what the correct paths for Heimdall src should be.
# Needed by PHPStan for symbol discovery.
#
#  phpstan:
#    name: PHPStan
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#        with:
#          path: src
#
#      - name: Checkout Heimdall repo for dependencies
#        uses: actions/checkout@v4
#        with:
#          repository: linuxserver/Heimdall
#          path: ./heimdall-src
#      
#      - uses: php-actions/phpstan@v3
#        with:
#          path: src/
#          configuration: src/phpstan.neon
